Add unit tests to module
MonssafToukal/SolverParameters.jl pull request #7
Opened 2022-11-06 18:58 UTC by MonssafToukal

2022-11-08 15:43 UTC, tmigot requested changes
That looks great, thanks! I have a couple of comments to improve.

2022-11-08 15:43 UTC, tmigot commented on .vscode/settings.json
> +}
I don't think we need this.

2022-11-08 15:43 UTC, tmigot commented on src/parameters.jl
> +  end
Example:
```julia
  mutable struct MySolverParameterSet <: AbstractParameterSet
    η₁::Parameter(1.0e-5, RealInterval(0, 1; lower_open=true, upper_open=false))
  end
```

2022-11-08 15:43 UTC, tmigot commented on src/parameters.jl
> +  end
Use the "```" delimiters for a block code

2022-11-08 15:43 UTC, tmigot commented on src/parameters.jl
>  It contains specific fields that can be given to `NOMAD`.
```suggestion

```

2022-11-08 15:43 UTC, tmigot commented on test/test_parameters.jl
> +@testset "Parameters" verbose=true begin
I think we also want to do this tests for all the different types not only `Real`

2022-11-08 15:44 UTC, tmigot commented
Any idea why the tests fail with Julia 1.6?

2022-11-08 15:45 UTC, tmigot commented on src/parameters.jl
> +name(parameter::Parameter{T}) where {T} = parameter.name
Are these functions tested?

2022-11-08 21:54 UTC, MonssafToukal commented
> Any idea why the tests fail with Julia 1.6?

I think it's because I use regex to check that the correct error message is thrown? I'll change it to a `occursin("error msg", error)` and see if it does the same.

2022-11-09 18:42 UTC, MonssafToukal commented
@tmigot Let me know if anything is missing!

2022-11-09 23:14 UTC, tmigot approved these changes
Great job, thanks!

2022-11-11 16:25 UTC, merged